import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import localFont from "next/font/local";
import FooterImage from "@/components/layout/FooterImage";
import TasksToday from "@/components/layout/TasksToday";

const inter = localFont({
  src: "../fonts/InterFont.ttf",
  Weight: "400, 500, 600, 700, 800",
});

const manrope = localFont({
  src: "../fonts/ManropeFont.ttf",
  Weight: "400, 500, 600, 700, 800",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${manrope.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <TasksToday />

          <Footer />
          <FooterImage />
        </ThemeProvider>
      </body>
    </html>
  );
}
